# Generated by Django 4.2.3 on 2025-04-26 04:04

from django.db import migrations

def set_default_allergen_data(apps, schema_editor):
    # Get the OrderItem model
    OrderItem = apps.get_model('users', 'OrderItem')
    
    # Get all order items
    order_items = OrderItem.objects.all()
    
    # Set a default value for all existing items
    for item in order_items:
        if not item.allergy_info:
            item.allergy_info = 'Not specified'
            item.save()

class Migration(migrations.Migration):
    dependencies = [
        ('users', '0013_remove_orderitem_has_allergens_and_more'),
    ]

    operations = [
        migrations.RunPython(set_default_allergen_data),
    ]
