# Generated by Django 4.2.3 on 2025-04-25 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_order_created_at_order_delivery_date_order_note_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="supplied_orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
