# Generated by Django 4.2.3 on 2025-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_order_supplier"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
