# Generated by Django 5.2 on 2025-04-25 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_itemoffer_remove_offer_created_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="order_item_id",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="accepted_supplier",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="supplier_price",
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("new_bid", "New Bid"),
                    ("bid_accepted", "Bid Accepted"),
                    ("order_status_change", "Order Status Change"),
                    ("generic", "Generic Notification"),
                ],
                max_length=50,
            ),
        ),
    ]
