# Generated by Django 4.2.3 on 2025-04-26 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_remove_notification_order_item_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="allergens",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
