# Generated by Django 4.2.3 on 2025-04-26 03:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_orderitem_allergens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="allergens",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="has_allergens",
            field=models.BooleanField(default=False),
        ),
    ]
