# Generated by Django 4.2.3 on 2025-04-26 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_remove_orderitem_allergens_orderitem_has_allergens"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="has_allergens",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="allergy_info",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
