services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    volumes:
      - ./db.sqlite3:/app/db.sqlite3 
      - static_volume:/app/staticfiles 
    ports:
      - "8000:8000"
    restart: always
    environment:
      - DEBUG=True
      - DJANGO_SETTINGS_MODULE=mikail_platform.settings

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

volumes:
  static_volume: